### ISSUE TITLE
Milestone 2 - Meeting Notes

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/online_news_popularity#11]
### Milestone 2 Tasks:
- [x]  Script 1: Download
    - Completed (TA feedback pending)
- [x]  Script 2: Data cleaning and pre-processing - JENNIFER
- [x]  Script 3: EDA visualizations and tables - LINHAN
- [x]  Script 4: Statistical Analysis - NAGRAJ
- [x]  Script 5: Summary of Key findings - ALL
    - [x]  Summary - JENNIFER
    - [x]  Introduction - JENNIFER
    - [x]  Methods 
        - [x]  Data - JENNIFER
        - [x]  Analysis - LINHAN (EDA), NAGRAJ (Regression)
    - [x]  Results - LINHAN (EDA), NAGRAJ (Regression)
    - [x]  Discussion - ALL
    - [x]  References - ALL

**Project Organization:**

- [x]  Update README File:
    - [x]  Project summary - JENNIFER
    - [x]  How to run analysis (order of scripts and inputs) - LINHAN
        - [ ]  Dependency diagram (optional)
    - [x]  List software dependencies - NAGRAJ

**Submission Notes:**

- [x]  Add Release (0.1.0) - Linhan

**Roles:**

- [x]  Scribe - Jennifer
- [x]  Proofreader/Submitter - Linhan

Next Meeting: November 26 at 8pm

**Comment by nrao944** [comment]
What factors are we going to look at while selecting features?
1. Transformations for variables
2. Economic rationale
3. Statistical significance

**Comment by jennifer-hoang** [comment]
Data Cleaning Ideas:
- Outliers (1.5 times the IQR method)
- URLs: extract date?
- Transformations:
    - Shares/Day? 
    - log transformation of Shares/Day?

**Comment by lipcai** [comment]
EDA visualizations and tables ideas:
  Based on python and altair
  Double check with the data clean
  Deal with the data and analysis part of key findings

**Comment by jennifer-hoang** [comment]
Something to look into:
- Using `SelectFromModel(Ridge(), threshold = "median")` to select features before inputting into LinearRegression?
