### ISSUE TITLE
Milestone 1 - Meeting Notes

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/online_news_popularity#2]
## MEETING MINUTES: 
Date: November 17, 2021 
Edited: November 20, 2021 
### Action Items:
- [x] Teamwork Contract  ALL 
- [x] Project Set up
  - [x] Github repo: file + directory structure JENNIFER #1 
- Repo Files:
  - [x] Code of conduct    - NAGRAJ #3 
  - [x] Contributing file - LINHAN #4 
  - [x] License file - LINHAN #4
  - [x] Project Proposal - TYPE UP A BLURB - NAGRAJ #5 
    - [x] Find question + dataset 
  - [x] Script to Download and Save Data - JENNIFER #1 
  - [x] Exploratory Data Analysis - NAGRAJ/LINHAN #6 #8

**Comment by nrao944** [comment]
Some helpful links for documents to be reviewed during our meeting:

1. Meeting Minutes: https://docs.google.com/document/d/14fLDTUcn5fCYyvp6kirQYDi8ObtmB8bIr5-izaDc9_E/edit
2. Teamwork Contract: https://docs.google.com/document/d/1bopdtxNyOSsQhV2g9CPA6QZsbbvx57YFPRyE3iLJm5w/edit#
3. Code of Conduct: https://docs.google.com/document/d/1pNdx2mnOKNCpZp7T6CLOoQnYHKr3-idHQgs7aCOh36U/edit#
4. Contributing file: Link from Linhan (currently in Teamwork contract)
5. License file: Link from Linhan (currently in Teamwork contract)
6. Project Proposal: Attached to this message
7. GitHub Repo: https://github.com/UBC-MDS/online_news_popularity (Jennifer will help us show how to upload our files, forking, or any other tasks)
8. Script to Download and Save Data: Jennifer
9. Exploratory Data Analysis: Being done by Nagraj (TBD), Maybe Linhan has some updates?

See you all soon!

**Comment by nrao944** [comment]
TO DO LIST:

1. Linhan submits EDA and License File in the appropriate location. 
2. Nagraj submits README.md and EDA in appropriate location. 

Let me know if I missed anything!
