### ISSUE TITLE
Milestone 3 - Meeting Notes

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/online_news_popularity#25]
Action Steps:

- [x] Create Makefile - Jennifer
- [ ] Address TA Feedback in Report - Nagraj
- [ ] Address EDA TA feedback - Linhan

**Comment by lipcai** [comment]
Change the eda part and make new tables and plots
