### ISSUE TITLE
Milestone 4 - Meeting Notes

### ISSUE THREAD

**Issue by jennifer-hoang** [UBC-MDS/online_news_popularity#34]
Action Items

- [x] Dockerfile:
  - Include instructions on how to run make
  - Pin base image to SHA ver
- [x] Dependency Graph
- [x] Address Feedback (min 4)
  - [x] Add links to commits that address feedback

**Comment by lipcai** [comment]
- [ ] Include 4 suggestions of the reviewers (in the review reopo issue, just comment under other reviews to tell what you have updated)
- [ ] Double check work is possible to reproduce
- [ ] The URL of the release. The URL of the repository. The link to the issue where you received the project peer reviews and you have pasted the links to the commits.

**Comment by nrao944** [comment]
1. Nagraj updates the report with the new table and figures.
2. Linhan does the Dependency Graph.
3. Jennifer + Nagraj work on the Docker independently and update the team.
4. Comments to be updated by Nagraj in the Issues for Peer-Review.
